name: Test Composite action

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run local action
        uses: ./.github/actions/my-action