name: Workflow de prueba

on: [push, pull_request]

jobs:
  file-creation:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
      
      - name: touch file
        run: touch file.txt

      - name: set text
        run: echo "Hello world" > file.txt
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print job2
        run: echo "Job2 running"
    
  job3:
    runs-on: ubuntu-latest
    needs: [file-creation]
    steps:
      - name: Print job3
        run: echo "Job3 running"
