name: Workflow de prueba

on: [push, pull_request]

jobs:
  file-creation:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
      
      - name: touch file
        run: touch file.txt

      - name: set text
        run: echo "Hello world" > file.txt
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print job2
        run: echo "Job2 running"

  
    
  job3:
    runs-on: ubuntu-latest
    needs: [file-creation]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: ./node_modules
      - run: npm install express
      - run: npm install cors

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Node version
        run: node --version
      - name: LS
        run: |
          chmod +x script.sh
          ./script.sh
            
