name: Workflow de prueba

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print job2
        run: echo "Job2 running"
